services:
    app:
        build: .
        container_name: poll-story-telegram-bot
        env_file:
            - .env
        volumes:
            - .story_state.yaml:/app/story_state.yaml
            - ./logs:/app/logs
        restart: unless-stopped
