services:
    app:
        build: .
        container_name: poll-story-telegram-bot
        env_file:
            - .env
        volumes:
            - ./state:/app/state
            - ./logs:/app/logs
        restart: unless-stopped
