services:
    app:
        image: glebosotov/poll-story-telegram-bot:latest
        container_name: llm-bot
        volumes:
            - .env:/app/.env
            - ./logs:/app/logs
            - ./state:/app/state
        restart: unless-stopped
